-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 31, 2021 at 08:40 AM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `plantdiseasedetection`
--

-- --------------------------------------------------------

--
-- Table structure for table `dataset`
--

CREATE TABLE `dataset` (
  `id` int(50) NOT NULL,
  `prediction` varchar(100) NOT NULL,
  `common_name` varchar(100) NOT NULL,
  `scientific_name` varchar(100) NOT NULL,
  `caused_by` varchar(500) NOT NULL,
  `treatment` varchar(5000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `dataset`
--

INSERT INTO `dataset` (`id`, `prediction`, `common_name`, `scientific_name`, `caused_by`, `treatment`) VALUES
(1, 'Disease: Apple Scab', 'Apple Scab', 'Malus Domestica', 'Apple Scab is caused by the fungus Venturia inaequalis. The fungal disease forms pale yellow or olive-green spots on the upper surface of leaves. Dark, velvety spots may appear on lower surface. Severely infected leaves become twisted and puckered and may drop early in summer.', '\r\nPlanting disease resistant varieties is the best way to manage scab.Apples with good resistance include Akane, Chehalis, Liberty, Prima and Tydeman Red.Fungicides like Bonide Captan, wettable sulfur, summer lime sulfur or Spectracide Immunox can be used to manage apple scab.Proper timing of sprays is needed for fungicides to control disease.Postharvest foliage sprays are a very useful supplement to scab control, especially after a season of high scab incidence.'),
(2, 'Disease: Apple Black Rot Canker', 'Apple Black Rot Canker', 'Malus domestica', 'The fungus Botryosphaeria obtusa can cause devastating losses to apples and crabapples over a wide geographical range and in warm humid climates. The fungus is skilled at lurking in dead apple tissue. It commonly colonizes apple limbs that died after fire blight and can enter through variety of wounds-including pruning cuts. This fungus causes reddish brown cankers that are slightly below the level of the healthy bark around it.', 'Remove them by cutting them out or pruning away the affected limbs at least six inches (15 cm.) beyond the wound. Destroy all infected tissue immediately and keep a watchful eye out for new signs of infection. Although general-purpose fungicides, like copper-based sprays and lime sulfur, can be used to control black rot, nothing will improve apple black rot like removing all sources of spores'),
(3, 'Disease: Apple Cedar Rust', 'Apple Cedar Rust', 'Malus domestica', 'Cedar apple rust (Gymnosporangium juniperi-virginianae) is a fungal disease that requires juniper plants to complete its complicated two year life-cycle. Spores overwinter as a reddish-brown gall on young twigs of various juniper species. ', 'Rake up and dispose of fallen leaves and other debris from under trees.Treat most fungal and bacterial diseases with SERENADE Garden.Use Bonide Orchard Spray containing sulfur and pyrethrins for insect attacks and fungal problems.\r\n'),
(4, 'Disease: Arjun Leaf Spot', 'Arjun Leaf Spot', '	\r\nTerminalia arjuna	\r\n\r\n \r\n', '\r\nThis disease is believed to be caused by deficiency of copper. Withering of leaves is observed in young and tender leaves, which show crinkling soon after expansion from the buds.	\r\n\r\n\r\n', '	\r\n1)Proper cultural operations and field sanitation.\r\n\r\n2)Plucking and burning of diseased leaves.\r\n\r\n3)Spray of Carbendazim @ 0.1% or 0.5% Biltox or 0.5% Diathane M-45.\r\n\r\n'),
(5, 'Disease: Bael Chlorosis', 'Bael Chlorosis', 'Aegle marmelos', 'A common cause of chlorosis is a deficiency of iron or manganese, both of which are present but unavailable in high pH soils (pH>7.2). Iron and manganese are needed by plants to form chlorophyll and to complete photosynthesis.\r\n', 'soil application of elemental sulfur combined with ferrous (iron) sulfate,iron chelates; foliar sprays containing ferrous sulfate or chelated iron; or trunk injection of ferric ammonium citrate or iron sulfate'),
(6, 'Disease: Black Plum Anthracnose', 'Black Plum Anthracnose', 'Syzygiumc umini', '	\r\nAnthracnose disease is induced by the fungus Colletotrichum lagenarium.\r\nAnthracnose generally appears first as small, irregular yellow or brown spots. These spots darken as they age and may also expand, covering the leaves.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n', '\r\n\r\nPrune out all infected branches in late winter and destroy them by burning, burying, or throwing them away. Remove at least 3-4 inches of healthy tissue below each knot to ensure elimination of the fungus\r\n'),
(7, 'Disease: Blackboard Foliar Galls', 'Blackboard Foliar Galls', 'Alstonia scholaris', 'Morphological, Anatomical and Biochemical alterations in foliar galls of Alstonia scholaris R. Br. induced by the insect Pauropsyllatuberculata (Psyllidae)', 'Prune and destroy gall-infested twigs and branches. Burn or step on the galls to kill the developing larvae. Place gall remains in a tightly sealed baggie or trash bag and discard immediately. Rake and destroy gall-infested fallen leaves.'),
(8, 'Disease: Broccoli Clubroot', 'Broccoli Clubroot', 'Brassica oleracea', 'Clubroot is caused by the pathogen Plasmodiophora brassicae. It affects plants of the brassica family which includes broccoli, broccolini, cauliflower, cabbage, Chinese cabbage, turnips and Brussels sprouts as well as weeds such as wild radish and wild turnip.', 'Plant the broccoli in well-drained soil only. And If you have clay soil with poor drainage, improve it by adding organic matter.Check the soil pH and maintain a soil pH of 6.8 or higher, which can help prevent clubroot.'),
(9, 'Disease: Cherry Powdery Mildew', 'Cherry Powdery Mildew', 'Prunus avium', 'Powdery mildew of sweet and sour cherry is caused by Podosphaera clandestina, an obligate biotrophic fungus. Mid- and late-season sweet cherry (Prunus avium) cultivars are commonly affected, rendering them unmarketable due to the covering of white fungal growth on the cherry surface ', 'Spray on plants every one to two weeks. Potassium bicarbonate– Similar to baking soda, this has the unique advantage of actually eliminating powdery mildew. Potassium bicarbonate is a contact fungicide which kills the powdery mildew spores quickly.'),
(10, 'Disease: Chinar Leaf Spot', 'Chinar Leaf Spot', 'Platanus orientalis', 'A leaf spot is a limited, discoloured, diseased area of a leaf that is caused by fungal, bacterial or viral plant diseases, or by injuries from nematodes, insects, environmental factors, toxicity or herbicides. These discoloured spots or lesions often have a centre of necrosis or cell death', 'Traditional treatment by spraying with a mild solution of bicarbonate of soda (baking soda), using ½ teaspoon per gallon (2.5mL per 4L) of water. Safer-Brand Garden Fungicide can kill existing leaf spot and control the future outbreaks. Remove infected leaves and dead twigs and the remainder of the plant can be treated to prevent further damage, using a copper fungicide.'),
(11, 'Disease: Chinese Cabbage Fusarium Wilt', 'Chinese Cabbage Fusarium Wilt', 'Brassica rapa subsp. pekinensis', 'Fusarium wilt, widespread plant disease caused by many forms of the soil-inhabiting fungus Fusarium oxysporum', 'Remove and dispose of affected plants immediately, Whenever possible, remove and replace fusarium-infected garden soil. Mycostop is a biological fungicide that will safely protect crops against wilt caused by Fusarium.'),
(12, 'Disease: Corn Cercospora Leaf Spot', 'Corn Cercospora Leaf Spot', 'Zea mays	\r\n\r\n', 'The gray leaf spot disease is caused by the fungus Cercospora zeae-maydis. It survives in plant residues in the soil for long periods of time. During the spring, the spores are carried onto the lower leaves by rain splashes and wind.', 'Destroy infected crop residue from the field. Use of resistant/tolerant hybrids. Foliar spray of Mancozeb @ 2.5 g/ L of water after about 15 days after sowing is effective and provide two more sprays at 10-day intervals or immediately after symptoms appearance.\r\n'),
(13, 'Disease: Corn Common Rust', 'Corn Common Rust', 'Zea mays	\r\n\r\n', 'The disease is caused by the fungus Puccinia sorghi. The fungus overwinters in an alternate host (a species of Oxalis) and releases spores during the spring. The spores can be transported over great distances by winds and rain.', 'If the corn begins to show symptoms of infection, immediately spray with a fungicide. Products containig mancozeb, pyraclostrobin + fluxapyroxad, azoxystrobin + propiconazole, trifloxystrobin + prothioconazole can be used to control the disease.'),
(14, 'Disease: Corn Leaf Blight', 'Corn Leaf Blight', 'Zea mays', 'corn leaf blight (CLB) or Turcicum leaf blight (TLB) is a foliar disease of corn (maize) caused by Exserohilum turcicum, the anamorph of the ascomycete Setosphaeria turcica. With its characteristic cigar-shaped lesions, this disease can cause significant yield loss in susceptible corn hybrids.', 'Plant corn with enough space for airflow and water in the morning so leaves can dry throughout the day. Foliar fungicides may be applied early in the growing season to corn seedlings as a risk-management tool for corn leaf blight. Combination of rotating away from corn for one year followed by tillage is recommended to prevent leaf blight.'),
(15, 'Disease: Cucumber Bacterial Wilt', 'Cucumber Bacterial Wilt', 'Cucumis sativus', 'Cucumber bacterial wilt is caused by the bacterium, Erwinia tracheiphila, and is characterized initially by wilting and drying of individual leaves, especially those exhibiting cucumber beetle injury.', 'Protect plants with netting. Remove and destroy plant material when symptoms of wilting are first noticed. Grow susceptible crops on rotation every third year. Grow varieties that tolerate bacterial wilt like butternut or acorn squash and Saladin or County Fair 83 cucumbers. Dust plants with insecticide in the spring before the cucumber beetles have a chance to lay eggs.\r\n'),
(16, 'Healthy: Apple Leaf', ' Apple\r\n', 'Malus domestica', 'Healthy', 'NIL'),
(17, 'Healthy: Arjun Leaf', 'Arjun Leaf', 'Terminalia arjuna', 'Healthy', 'NIL'),
(18, 'Healthy: Basil Leaf', 'Basil', 'Ocimum basilicum', 'Healthy', 'NIL'),
(19, 'Healthy: Black Plum Leaf', 'Black Plum Leaf', 'Syzygium cumini', 'Healthy', 'NIL'),
(20, 'Healthy: Blackboard', 'Blackboard', 'Alstonia scholaris', 'Healthy', 'NIL'),
(21, 'Healthy: Blueberry', 'Blueberry', 'Cyanococcus', 'Healthy', 'NIL'),
(22, 'Healthy: Broccoli', 'Broccoli', 'Brassica oleracea var. italica', 'Healthy', 'NIL'),
(23, 'Healthy: Cherry', 'Cherry', 'Prunus avium', 'Healthy', 'NIL'),
(24, 'Healthy: Chinar', 'Chinar', 'Platanus orientalis', 'Healthy', 'NIL'),
(25, 'Healthy: Chinese Cabbage', 'Chinese Cabbage', 'Brassica rapa subsp. pekinensis', 'Healthy', 'NIL'),
(26, 'Healthy: Corn', 'Corn', 'Zea mays', 'Healthy', 'NIL'),
(27, 'Disease: Cucumber Thrips', 'Cucumber Thrips', 'Cucumis sativus\r\n', 'Thrips are miniscule, straw-colored narrow insects with fringed wings. thrips penetrate the cells of a plant such as cucumber or tomato, and remove their contents. This causes severe damage to the plant characterized by deformation, scars and silvery patches. Extreme thrip infestations can kill your cucumber plant, but the correct control methods can eliminate thrips without harming your plant.', 'The bug  blaster to hose off plants with a strong, encompassing spray of water to reduce pest numbers. To keep thrips populations under control, try using yellow or blue sticky traps. For fruit trees, Spray dormant oil on the trees. Using a mild insecticide like insecticidal soap or neem oil, or by pruning the flowers. Use a pyrethrin spray or another type of oil-based spray. \r\n'),
(28, 'Disease: Cucumber White Mold', 'Cucumber White Mold', 'Cucumis sativus', 'White mold is caused by a soil borne fungus, Sclerotinia sclerotiorum. White mold disease also displays white mold; this is more fluffy and appears under humid weather conditions only. Small black dots appear within the fluffy white mold; these are the hard resting bodies of the fungus that causes white mold. Stems of infected cucumber plants can rot; cucumbers can rot and turn watery. When cut open, infected fruit may contain the small black fungal bodies.', 'Apply fertilizer based on soil test results. Avoid over-applying nitrogen. Provide good air movement around plants through proper spacing, staking of plants and weed control. Apply fungicide after finding the first spot of white mold. apply sulfur products to both the upper and lower surface of the leaves. Mix two teaspoons of organic neem oil with a half-gallon of water into a sprayer, and apply liberally on the infected plant every few days until the mold is gone.\r\n\r\n'),
(29, 'Disease: Grape Black Rot', 'Grape Black Rot', 'Vitis', 'Grape black rot is a fungal disease caused by an ascomycetous fungus, Guignardia bidwellii, that attacks grape vines during hot and humid weather', 'Cultivating the soil under the vine shortly before bud-break in the spring. This can bury spores, thus preventing them from reaching the plant. Fungicides applied early in the growing season are a critical component of a black rot management.\r\n\r\n'),
(30, 'Disease: Grape Blister Mite', 'Grape Blister Mite', 'Vitis', 'The blister-like outgrowths on leaves are caused by Colomerus vitis. Despite the evident symptoms, it is not considered a major pest of grape. The tiny and sap-sucking mites affect predominantly grapevine.', 'The predatory mite Galendromus occidentalis feeds on blister mites and can reduce their numbers. A number of other chemical sprays used for the control of leafhoppers and spider mites also stem the population of blister leaf mites. Spirotetramat can be used against blister mites.\r\n'),
(31, 'Disease: Grape Esca', 'Grape Esca', 'Vitis', 'Esca is a grape disease of mature grapevines. It is a type of grapevine trunk disease. The fungi Phaeoacremonium aleophilum, Phaeomoniella chlamydospora and Fomitiporia mediterranea are associated with the disease.', 'Strict sanitation and protection of all wounds from pruning to grafting will help protect vines during nursery production. Frequently disinfest pruning shears, hydration tanks, grafting machines, and callusing rooms. Grow mother vines in well-drained soil or raised beds. Use drip irrigation that does not over-wet the root crown. Remove diseased debris from the vineyard and destroy them. Monitor the vineyard  in Spring, and look for dead spurs or for stunted shoots.\r\n\r\n'),
(32, 'Healthy: Grape', 'Grape', 'Vitis', 'Healthy', 'NIL'),
(33, 'Disease: Grape Leaf Blight', 'Grape Leaf Blight', 'Vitis', 'The yellow-green disease spots gradually appear on the fronts of the grape leaves with downy mildew, and white frosty mildew appears on the backs of the leaves. Leaf blight produces dark brown patches on the surface of grape leaves', 'Use grape cultivars with disease tolerance. Practice sanitation by removing mummies from the trellis and off the ground and by pruning out diseased vines. Manage the canopy with pruning and leaf removal to reduce relative humidity.\r\n'),
(34, 'Disease: Grape Nitrogen Deficiency', 'Grape Nitrogen Deficiency', 'Vitis', 'Nitrogen deficiency Water shortage and some injuries of roots or trunks caused mechanically or by parasites that hinder the absorption and transport of nutrients lead sooner or later to stunted growth and lighter colored leaves, which may be confused with N deficiency.', 'Soil application of urea @ 20-60 Kg/acre. Foliar spray of urea (0.3 – 0.5%) 1- 4 times along the growing season , depending on the deficiency severity. Nitrogen deficiency can be corrected by applying either organic or inorganic fertilizers, but nitrate or ammonium-based fertilizers work the most quickly. Replace nitrogen in the soil by applying a balanced feed in spring to raise general nutrient levels.\r\n'),
(35, 'Disease: Grape Powdery Mildew', 'Grape Powdery Mildew', 'Vitis', 'Powdery mildew, caused by the fungus Erysiphe necator (syn. Uncinula necator), is one of the most prevalent and easily recognized plant diseases afflict- ing grape vines. It appears as a dusty white-gray or greenish-white coating on leaf surfaces or other above-ground plant parts.', 'Apply a 1-2% oil treatment to the vines within 2 days of the water application. In general, petroleum-based oils work better than plant-based oils. Powdery mildew can effectively be treated by fungicides. A regiment of preventative fungicides, labeled for powdery mildew on edibles, can be started in early spring and re-applied every 7-14 days until the grape plant begins to bloom\r\n'),
(36, 'Disease: Guava Wilt', 'Guava Wilt', 'Psidium guajava', 'The disease is soil-borne and is difficult to control. Wilt is predominantly caused by the species of Fusarium, of which F. oxysporum is generally the main cause. Appearance of light yellow foliage with loss of turgidity and epinasty. Plants, at a later stage, show unthriftyness. Subsequently, premature shedding and defoliation.', 'There’s no cure for wilt infections in plants, but good nutrition, including heavy feedings of nitrogen after fruiting, and protecting roots from damage can help stave off the disease. The disease could be controlled by proper sanitation in the orchard. Wilted trees should be uprooted, burnt and trench should be dug around the tree trunk. Intercropping with turmeric or marigold restrict the wilting of guava.\r\n'),
(37, 'Healthy: Guava', 'Guava', 'Psidium guajava', 'Healthy', 'NIL'),
(38, 'Healthy: Jatropha', 'Jatropha', 'Jatropha curcas', 'Healthy', 'NIL'),
(39, 'Disease: Jatropha Leaf Spot', 'Jatropha Leaf Spot', 'Jatropha curcas', 'leaf Spot Disease Caused by Aspergillus tubingensis on Jatropha curcas.Spots were irregular, gradually increased in size and number, turned dark brown and dry, and finally the entire infected leaves turned yellow and fell.', 'Remove infected leaves and dead twigs. Use fungicides if needed.Keep foliage dry. Avoid overhead watering.\r\n'),
(40, 'Disease: Lemon Citrus Canker', 'Lemon Citrus Canker', 'Citrus limon', 'Citrus canker, caused by the bacterium Xanthomonas citri subsp. citri, affects the leaves, twigs and fruit of citrus plants causing the leaves to drop and unripe fruit to fall to the ground.', 'Burn infected trees and use resistant citrus varieties. Spray with liquid copper fungicide as a preventative for treating citrus canker lemon disease. Use good sanitation practices to reduce potential disease spread. If you suspect that a citrus plant has citrus canker, report the tree to TDA. Remove and destroy diseased plants to eliminate potential bacteria for future infections.\r\n'),
(41, 'Disease: Lemon Citrus Leaf Miner', 'Lemon Citrus Leaf Miner', 'Citrus limon', 'Symptoms are caused by the feeding activity of the larvae of the citrus leafminer, Phyllocnistis citrella. The adults are tiny, brownish or gray moths with heavily fringed wings and a typical dark spot on the top of the front wing.', 'Organic insecticides containing spinosad, fish oil resin soap and Pongamia oil may be used as foliar spray applications to control the infestation by citrus leaf miner. Neem oil can be applied to deter the moths from laying their eggs on the leaves. Insecticides of the synthetic pyrethroid family were also used against this pest. Apply a systemic product containing imidacloprid and labeled for use on citrus trees (ex. Bayer Advanced Fruit, Citrus, and Vegetable Insect Control) to the ground around the base of citrus trees once per year in the spring.\r\n'),
(42, 'Healthy: Lemon', 'Lemon', 'Citrus limon', 'Healthy', 'NIL'),
(43, 'Disease: Mango Anthracnose', 'Mango Anthracnose', 'Mangifera indica', 'Mango anthracnose is caused by the fungus Colletotrichum gloeosporioides var minor (also known by the name of its perfect stage Glomerella cingulata var minor). Spore production by this fungus is favoured by wet or humid weather. The dispersal of these spores is particularly favoured by rain and wind.', 'Apply a systemic product containing imidacloprid and labeled for use on citrus trees (ex. Bayer Advanced Fruit, Citrus, and Vegetable Insect Control) to the ground around the base of citrus trees once per year in the spring. Spray one of the following: Difenoconazole @30 ml/100 litre water , Thiophenate methyl @200 gm/100 litre water , Fostyl aluminium @ 500 gm/100 litre of water.'),
(44, 'Healthy: Mango', 'Mango', 'Mangifera indica', 'Healthy', 'NIL'),
(45, 'Disease: Olive Anthracnose', 'Olive Anthracnose', 'Olea europaea', 'Olive anthracnose, caused by Colletotrichum spp., affects olive (Olea europaea L.) fruit at maturity. Symptoms are dark sunken lesions, covered with orange spore masses.If the diseased fruits are harvested, the quality of the olive oil produced is degraded.', 'To control Anthracnose in olives is to apply a preventative spray of copper oxychloride to the fruit and the foliage. In areas where disease pressure is high, regular copper sprays every 6-8 weeks throughout the growing season may be required. The olive fly makes wounds in the olive that facilitate the entry and development of the fungus. Therefore, effective control of the olive fly is essential against the disease\r\n'),
(46, 'Healthy: Olive', 'Olive', 'Olea europaea\r\n', 'Healthy', 'NIL'),
(47, 'Disease: Olive Tree Leaf Moth', 'Olive Tree Leaf Moth', 'Olea europaea', 'the olive leaf moth, Palpita unionalis (Hübner) (Lepidoptera: Pyralidae: Pyraustinae) was a secondary pest of olive (Oleae europea L.; Lamiales). The damage to buds, leaves and fruits are caused by three different generations of larvae of the species Prays oleae.', 'Solutions based on Bacillus thuringiensis kurstaki have also been shown to decrease olive moth numbers. Pheromone traps are very effective in catching adult moths and should be installed in the early spring. Apamarales hemara and Oomyzus sp are the ones that control this pest present in the olive grove.\r\n\r\n'),
(48, 'Disease: Orange Black Spot', 'Orange Black Spot', 'Citrus sinensis', 'Citrus black spot (CBS) is a citrus disease caused by the fungus Phyllosticta citricarpa (previously known as Guignardia citricarpa). This fungus affects citrus plants throughout subtropical climates, reducing both fruit quantity and quality.', 'A number of copper products such as copper oxychloride Demildex can be used against this pathogen. Treatments with quazatine or imazalil decrease the viability of the pathogen in blac spot lesions. Fungicides such as strobilurins, dithiocarbamates and benzimidazoles are also eficient against the fungus.\r\n'),
(49, 'Disease: Orange Canker', 'Orange Canker', 'Citrus sinensis', 'Citrus canker is a disease affecting Citrus species caused by the bacterium Xanthomonas axonopodis. Infection causes lesions on the leaves, stems, and fruit of citrus trees, including lime, oranges.', 'Citrus canker management involves the use of the timely applications of copper-containing products and windbreaks to hinder inoculum dispersal. Burn the infected leaves or trees. It can managed with preventive copper-based bactericides. Use resistant citrus varieties.\r\n'),
(50, 'Disease: Orange Citrus Leaf Miner', 'Orange Citrus Leaf Miner', 'Citrus sinensis', 'The citrus leaf miner is a major pest of citrus nursery and remains active from March to November. It causes injury to the citrus group of fruits such as lime, lemon, oranges and pomelo. Caterpillars of this insect feed on leaves by making shiny silvery serpentine mines.', 'Spray any one of the following insecticides: Dimethoate 30EC, profenofos 50EC, monocrotophos 36WSC, quinalphos 25EC at 2ml/litre of water, acephate 75SP at 2g/litre of water or imidacloprid 200SL at 375ml/ha.'),
(51, 'Disease: Orange Citrus Thrips', 'Orange Citrus Thrips', 'Citrus  sinensis', 'The damage is caused by the citrus thrip, Scirtothrips citri. Adults are small, orange-yellow with fringed wings.', 'Formulations containing abamectin, spinetoram, dimethoate, cyfluthrin can be used against citrus thrips. Sprays of formulations of spinosad with an organically approved oil , kaolin or sabadilla alkaloids applied with molasses or sugar bait can be used.'),
(52, 'Disease: Orange Citrus White Fly', 'Orange Citrus White Fly', 'Citrus  sinensis', 'Citrus leaves with sooty mold growing on honeydew excreted by the citrus whitefly, Dialeurodes citri (Ashmead). Whiteflies become a problem when they continually sap the plant of energy needed for growth.', 'Spray trees with an insecticidal soap for severe infestations. Mix 5 tablespoons of soap with 1 gallon of water. Organic Neem Oil can be sprayed on vegetables, fruit trees, leaves and flowers to kill eggs, larvae and adults. \r\n\r\n\r\n\r\n'),
(53, 'Disease: Orange Greening', 'Orange Greening', 'Citrus  sinensis', 'Citrus greening is spread by a disease-infected insect, the Asian citrus psyllid (Diaphorina citri Kuwayama or ACP), and has put the future of America\'s citrus at risk. Infected trees produce fruits that are green, misshapen and bitter, unsuitable for sale as fresh fruit or for juice.', 'Rapid removal of infected trees is the only way to stop the spread of the bacteria responsible. Using cultural methods such as antibacterial management, sanitation, removal of infected plants, frequent scouting, and most importantly, crisis declaration can be used.\r\n'),
(54, 'Healthy: Orange', 'Orange', 'Citrus  sinensis', 'Healthy', 'NIL'),
(55, 'Disease: Orange Melanose', 'Orange Melanose', 'Citrus  sinensis', 'Citrus melanose is caused by the plant-pathogenic fungus Diaporthe citri (anamorph = Phomopsis citri). It can create severe fruit rind blemishes, but the fungus does not normally affect the pulp. On leaves, the small, black, raised lesions are often surrounded by yellow halos and can cause leaf distortion.', 'Use sprays containing copper compounds to treat. Products based on mancozeb and fenbuconazole are also recommended. Strobilurin fungicides can be used. Remove the dead tree material regularly.\r\n'),
(56, 'Disease: Orange Red Scale', 'Orange Red Scale', 'Citrus  sinensis', 'The symptoms are caused by the feeding activity of the red scale, Aonidiella aurantii. It is a major pest of citrus worldwide, common in the tropics. They survive after harvest on wood and leaves, infesting new growth in the next growing season.', 'Red scale control can be accomplished with the use of pesticides, biological control via the introduction of indigenous parasitic wasps and an organically approved petroleum spray. Neem oil can also be used. To get rid of red scale prune and dispose of infested branches, twigs and leaves.\r\n'),
(57, 'Disease: Pea Chlorotic Lesions', 'Pea Chlorotic Lesions', 'Pisum sativum', 'Cowpea chlorotic mottle virus, known by the abbreviation CCMV, is a virus that specifically infects the cowpea plant, or black-eyed pea. The leaves of infected plants develop yellow spots, hence the name \"chlorotic\".', 'No fungicides effectively control this disease and no pea varieties with high resistance, control therefore relies on avoiding planting in infested fields; rotate crops to avoid build up of disease in soil.'),
(58, 'Healthy: Pea', 'Pea', 'Pisum sativum', 'Healthy', 'NIL'),
(59, 'Disease: Peach Bacterial Spot', 'Peach Bacterial Spot', 'Prunus persica', 'Bacterial spot, known also as bacteriosis, bacte- rial shothole, or shothole, is caused by the bacterium Xanthomonas campestris pv. pruni. Although primarily a peach and nectarine problem, this disease also occurs on apricots, plums and, to a lesser degree, cherries.', 'Compounds available for use on peach and nectarine for bacterial spot include copper, oxytetracycline and syllit+captan.\r\n\r\n'),
(60, 'Healthy: Peach', 'Peach', 'Prunus persica', 'Healthy', 'NIL'),
(61, 'Disease: Pear Lace Bug', 'Pear Lace Bug', 'Pyrus ', 'Azalea lace bug, Stephanitis pyrioides (Scott), belongs to a group of insects in the family Tingidae. The insects in this family generally live and feed on the underside of leaves. They have thin lacy outgrowths on their thorax, and have delicate lace-like forewings ', 'Treatments with insecticidal soap, narrow-range oil, and natural pyrenthrins can be used. Prune the infected tree parts and destroy the debris. Apply insecticide only when pests are present or expected to become too abundant.\r\n\r\n'),
(62, 'Disease: Pepper Bacterial Spot', 'Pepper Bacterial Spot', 'Capsicum annuum', 'Bacterial leaf spot, caused by Xanthomonas campestris pv. vesicatoria, is the most common and destructive disease for peppers. It is a gram-negative, rod-shaped bacterium that can survive in seeds and plant debris from one season to another.', 'Copper sprays can be used to control bacterial leaf spot, but these have to be combined with a plant resistance inducer, such as Regalia or Actigard, which can provide good protection from the disease. Beneficial microorganisms containing products, such as Serenade and Sonata, can reduce pepper leaf spot if used proactively. Copper and Mancozeb sprays can be used for control of bacterial leaf spot. Actigard (Syngenta Crop Protection) and Quintec (Dow AgroSciences) are also good preventives.\r\n\r\n'),
(63, 'Healthy: Pepper', 'Pepper', 'Capsicum annuum ', 'Healthy', 'NIL'),
(64, 'Disease: Pomegranate Cercospora Spot', 'Pomegranate Cercospora Spot', 'Punica granatum', 'The symptoms are caused by the fungus Pseudocercospora punicae. It can survive in plant debris and in infected stem portions of the plant. It is spread by wind borne spores. The disease emergence is favored by rainfall and water-saturated soil.', 'Spray the plants with appropriate fungicides with active ingredients such as thiophanate, carbendazim, or propiconazole.'),
(65, 'Healthy: Promegranate', 'Promegranate', 'Punica granatum', 'Healthy', 'NIL'),
(66, 'Disease: Potato Early Blight', 'Potato Early Blight', 'Solanum tuberosum', 'Early blight of potato is caused by the fungal pathogen Alternaria solani. The disease affects leaves, stems and tubers and can reduce yield, tuber size, storability of tubers, quality of fresh-market and processing tubers and marketability of the crop.', 'Trichoderma harzianum, T.viride, and Pseudomonas fluorescens are effective against the disease. Protectant fungicides such as maneb, mancozeb, chlorothalonil, and triphenyl tin hydroxide are also effective.\r\n'),
(67, 'Healthy: Potato', 'Potato', 'Solanum tuberosum\r\n', 'Healthy', 'NIL'),
(68, 'Disease: Potato Late Blight', 'Potato Late Blight', 'Solanum tuberosum', 'Late blight is caused by the oomycete Phytophthora infestans. Oomycetes are fungus-like organisms also called water molds, but they are not true fungi.', 'The severe late blight can be effectively managed with prophylactic spray of mancozeb at 0.25% followed by cymoxanil+mancozeb or dimethomorph+mancozeb at 0.3% at the onset of disease and one more spray of mancozeb at 0.25% seven days after application of systemic fungicides.'),
(69, 'Healthy: Raspberry', 'Raspberry', 'Rubus idaeus\r\n', 'Healthy', 'NIL'),
(70, 'Disease: Rice Bacterial Leaf Blight', 'Rice Bacterial Leaf Blight', 'Oryza sativa', 'Bacterial blight is caused by Xanthomonas oryzae pv. oryzae. It causes wilting of seedlings and yellowing and drying of leaves.\r\n', 'Use balanced amounts of plant nutrients, especially nitrogen. Ensure good drainage of fields and nurseries. Keep fields clean. Remove weed hosts and plow under rice stubble, straw, rice ratoons and volunteer seedlings, which can serve as hosts of bacteria. The least expensive and most effective method of control is to plant resistant cultivars.\r\n'),
(71, 'Disease: Rice Brown Spot', 'Rice Brown Spot', 'Oryza sativa', 'Brown spot is caused by the fungus Cochliobolus miyabeanus. Also called Helminthosporium leaf spot, it is one of the most prevalent rice diseases in Louisiana. When C. miyabeanus attacks the rice plants at emergence, the resulting seedling blight causes sparse or inadequate stands and weakened plants.', 'Use fungicides (e.g., iprodione, propiconazole, azoxystrobin, trifloxystrobin, and carbendazim) as seed treatments. For soils that are low in silicon, apply calcium silicate slag before planting. Monitor soil nutrients regularly and apply required fertilizers. Practice good sanitation in your fields to help avoid brown leaf spot of rice and plant disease-resistant varieties.\r\n\r\n'),
(72, 'Disease: Rice Leaf Smut', 'Rice Leaf Smut', 'Oryza sativa', 'Ustilaginoidea virens, Villosiclava virens, is a plant pathogen which causes the disease False Smut of rice which reduces both grain yield and grain quality.Infected rice kernels are always destroyed by the disease.', 'Cleaning up debris at the end of each growing season can prevent spread of leaf smut. Spraying of copper hydroxide at 2.5 gm per litre of water or propiconazole at 1.0 ml per litre will be more useful. Excess application of nitrogenous fertilizer should be avoided.\r\n'),
(73, '\r\nHealthy: Soybean', '\r\nSoybean', 'Glycine max', '\r\nHealthy', 'NIL'),
(74, 'Disease: Squash Powdery Mildew', 'Squash Powdery Mildew', 'Cucurbita', 'Powdery mildew, mainly caused by the fungus Podosphaera xanthii, infects all cucurbits, including muskmelons, squash, cucumbers, gourds, watermelons and pumpkins. In severe cases, powdery mildew can cause premature death of leaves, and reduce yield and fruit quality.', '\r\nSulfur and “Stylet” oil are effective products for powdery mildew control. Neem oil is also an effective combatant for managing powdery mildew. Fixed copper fungicides have also shown results in managing powdery mildew.\r\n'),
(75, 'Healthy: Strawberry', 'Strawberry', 'Fragaria ananassa', 'Healthy', 'NIL'),
(76, 'Disease: Strawberry Leaf Scroch', 'Strawberry Leaf Scroch', 'Fragaria ananassa', 'Leaf scorch is caused by the fungus Diplocarpon earliana. Symptoms of leaf scorch consist of numerous small, irregular, purplish spots or “blotches” that develop on the upper surface of leaves.', 'Copper-Count-N at 1.5 to 2 quart/100 gal water. Group M1 fungicide. Monterey Liqui-Cop at 1 to 2 teaspoons/gal water. Topsin 4.5 FL at 15 to 20 fl oz/A plus another fungicide.\r\n'),
(77, 'Disease: Tomato Bacterial Spot', 'Tomato Bacterial Spot', 'Solanum lycopersicum', 'Bacterial spot of tomato is caused by Xanthomonas vesicatoria, Xanthomonas euvesicatoria, Xanthomonas gardneri, and Xanthomonas perforans. These bacterial pathogens can be introduced into a garden on contaminated seed and transplants, which may or may not show symptoms', 'Copper sprays are most effective or copper plus mancozeb.Repeat it for 10 to 14 days. Remove the infected plants to prevent the spread. Apply a thick mulch around the plants to stop water from splashing bacteria from the soil onto the leaves.\r\n'),
(78, 'Disease: Tomato Brown Rugse Fruit Virus', 'Tomato Brown Rugse Fruit Virus', 'Solanum lycopersicum', 'Tomato brown rugose fruit virus is a plant virus in the genus Tobamovirus. The main hosts are tomato and peppers. The virus causes symptoms including mosaic and distortion of leaves and brown, wrinkly spots on fruits.', 'Removal and destruction of the infected plants should be carried out immediately. After infested plants are destroyed, sanitation measures are required.\r\n\r\n'),
(79, 'Disease: Tomato Cracking', 'Tomato Cracking', 'Solanum lycopersicum', 'Heavy rain, especially when preceded by dry weather, is the leading cause of fruit cracking and splitting in tomatoes. This type of damage is most likely to occur as tomatoes begin to ripen and you are anxiously anticipating harvest, though green fruit can be effected as well.', 'To minimize fruit cracking, blossom end rot, and leaf curling in tomatoes is to maintain even soil moisture levels by watering during drought. Most vegetables require around one inch of water per week to remain productive.'),
(80, 'Disease: Tomato Early Blight', 'Tomato Early Blight', 'Solanum lycopersicum', 'Early blight can be caused by two different closely related fungi, Alternaria tomatophila and Alternaria solani. Alternaria tomatophila is more virulent on tomato than A. solani, so in regions where A. tomatophila is found, it is the primary cause of early blight on tomato.', 'Fungicides with  protectant and curative properties such as mancozeb and chlorothalonil are registered for use against early blight on tomato. Use classic Bordeaux Mixture, Bonide Copper Fungicide Dust in form of spray or dust the powder.\r\n'),
(81, 'Healthy: Tomato', 'Tomato', 'Solanum lycopersicum\r\n', 'Healthy', 'NIL'),
(82, 'Disease: Tomato Late Blight', 'Tomato Late Blight', 'Solanum lycopersicum', 'Late blight is caused by the oomycete Phytophthora infestans. Oomycetes are fungus-like organisms also called water molds, but they are not true fungi. There are many different strains of P. infestans.', 'Fungicides specific to water molds must be used. Use a copper-based fungicide (mix 2 ounces of fungicide with a gallon of water) every 6 or 7 days. Use Serenade Graden. Fungicides that contain maneb, mancozeb, chlorothanolil or fixed copper can help protect plants from late tomato blight. Baking soda has fungicidal properties that can stop or reduce the spread of late blight\r\n'),
(83, 'Disease: Tomato Leaf Miner', 'Tomato Leaf Miner', 'Solanum lycopersicum\r\n', 'The tomato leaf miner is a species of moth which causes widespread damage to tomato crops by mining plant tissues, particularly the leaves. These mines are formed by the larva (small caterpillars).', 'Use neem bliss 100% cold pressed neem oil, garden dust, citrus leafminer lures. Use monterey garden insect spray, monterey BT, beneficial nematodes, yellow sticky traps.\r\n'),
(84, 'Disease: Tomato Leaf Mold', 'Tomato Leaf Mold', 'Solanum lycopersicum', 'The symptoms are caused by the fungus Mycovellosiella fulva, whose spores can survive without a host for 6 months to a year at room temperature (non-obligate). The symptoms usually start to appear 10 days after inoculation with the development of spots on both sides of the leaf blade.\r\n', 'The fungi Acremonium strictum, Dicyma pulvinata, Trichoderma harzianum and Trichothecium roseum are antagonistic and could be used to reduce its spread. Calcium chloride sprays are among the most highly recommended types for leaf mold. Copper-based fungicides can be used to control diseases on tomatoes.\r\n'),
(85, 'Disease: Tomato Mosaic Virus', 'Tomato Mosaic Virus', 'Solanum lycopersicum', 'Leftover plant debris is the most common contagion. Tomato mosaic virus of tomatoes can exist in the soil or plant debris for up to two years, and can be spread just by touch – a gardener who touches or even brushes up against an infected plant can carry the infection for the rest of the day', 'Spot treat with least-toxic, natural pest control products, such as Safer Soap, Bon-Neem and diatomaceous earth, to reduce the number of disease carrying insects. Avoid using tobacco products around tomato plants, and wash hands after using tobacco products and before working with the plants\r\n'),
(86, 'Disease: Tomato Nutritional Deficiencies', 'Tomato Nutritional Deficiencies', 'Solanum lycopersicum', 'These boron-deficient leaves show a light general chlorosis. Boron deficiency results in necrosis of meristematic tissues in the growing region, leading to loss of apical dominance and the development of a rosette condition. These deficiency symptoms are similar to those caused by calcium deficiency.', 'Nitrogen (N): this is essential for plant cell growth and chlorophyll – used in leaves and all the green parts of the plant – and is therefore essential for all vegetables. In particular vegetables grown for their leaves need a plentiful supply. Lack of nitrogen results in slow or spindly growth and leaves can yellow, often the older ones first.\r\nPhosphorus (P): essential for healthy roots and also for fruit to ripen. Lack of phosphorus shows up when growth is poor, leaves begin to have a blue/green tint or fall off and fruit and flowers are disappointingly small or late.'),
(87, 'Disease: Tomato Pith Necrosis', 'Tomato Pith Necrosis', 'Solanum lycopersicum', 'Tomato Pith Necrosis is caused by Pseudomonas corrugata and other soil-borne species of Pseudomonas. This disease generally occurs on early planted tomatoes growing when night temperatures are cool, the humidity is high, and the plants are growing vigorously because of excessive levels of nitrogen.', 'There is no way to treat pith necrosis once it has infected tomato plants. The only way to manage the disease is through prevention by avoiding conditions that favor the pathogen, specifically excessive nitrogen.'),
(88, 'Disease: Tomato Septoria Leaf Spot', 'Tomato Septoria Leaf Spot', 'Solanum lycopersicum', 'Septoria Leaf Spot of Tomato. Septoria leaf spot is caused by a fungus, Septoria lycopersici. It is one of the most destructive diseases of tomato foliage and is particularly severe in areas where wet, humid weather persists for extended periods.', 'Fungicides containing copper and potassium bicarbonate will contain the fungal disease and keep it from spreading. Use of Fungonil and Daconil can also be used. Ziram and copper products are a few other sprays useful against this disease.\r\n\r\n'),
(89, 'Disease: Tomato Spider Mites', 'Tomato Spider Mites', 'Solanum lycopersicum', 'Red spider mites mainly feed on plants which are closely related and in the same family as tomato. The mites increase rapidly in numbers during hot and dry conditions.', 'Use the Bug Blaster to wash plants with a strong stream of water and reduce pest numbers. Mix Pure Neem Oil with Coco-Wet and apply every 3-5 days to kill pest eggs indoors and interrupt the reproductive cycle. Insecticidal soap or botanical insecticides can be used to spot and treat heavily infested areas.\r\n'),
(90, 'Disease: Tomato Target Spot', ' Tomato Target Spot', 'Solanum lycopersicum', 'Target spot of tomato is caused by the fungal pathogen Corynespora cassiicola. The disease occurs on field-grown tomatoes in tropical and subtropical regions of the world.', 'The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the first spots are seen and continue at 10-14-day intervals until 3-4 weeks before last harvest. Apply fungal spray as a preventive measure early in the season or as soon as the disease is noticed.\r\n'),
(91, 'Disease: Tomato Yellow Leaf Curl Virus', 'Tomato Yellow Leaf Curl Virus', 'Solanum lycopersicum', 'Tomato yellow leaf curl virus (TYLCV) is a tomato (Solanum lycopersicum)-infecting plant virus transmitted by whitefly Bemisia tabaci1,2. It belongs to the genus Begomovirus of the family Geminiviridae and has a single-stranded circular DNA genome of about 2.8 kb encapsidated in a twinned icosahedral virion3.', 'Imidacloprid should be sprayed on the entire plant and below the leaves, eggs and flies are often found below the leaves. Spray every 14-21 days. Tomato leaf curl disease was managed through three non-chemical treatments viz., compost, nutrient enrich compost and multi-nutrients.\r\n'),
(92, '-', '-', '-', '-', '-'),
(93, 'Velvet Leaf Weed', 'Velvet Leaf Weed', 'Abutilon theophrasti', 'Occurs where the soil has been recently disturbed and the long dormant seeds are brought close to the soil surface.', 'If you\'re fighting a small stand of velvetleaf weeds, you can pull them by hand before the plant goes to seed. Pull the weeds when the soil is moist. Use a shovel, if necessary, as pieces of roots that remain in the soil will sprout new weeds. Pulling is more effective when the soil is moist.'),
(94, 'Disease: Watermelon Gummy Stem Blight', 'Watermelon Gummy Stem Blight', 'Citrullus lanatus', 'Watermelon gummy stem blight is caused by the fungus Didymella bryoniae. The disease is both seed and soil-borne. It can be present in or on infested seed, or overwinter for a year and a half on infected crop residue. Periods of high temperature, moisture and humidity foster the disease – 75 F.', 'Regular fungicide sprays may be necessary to control gummy stem blight during cool, rainy weather. Daconil fungicides from GardenTech brand offer highly effective three-way protection to prevent, stop, and control gummy stem blight.\r\n\r\n'),
(95, 'Healthy: Watermelon', 'Watermelon', 'Citrullus lanatus', 'Healthy', 'NIL'),
(96, 'Disease: Zucchini Gray Mold Rot', 'Zucchini Gray Mold Rot', 'Cucurbita pepo', 'Gray-mold rot or Botrytis blight, caused by the wide-spread fungus Botrytis cinerea, affects most vegetable and fruit crops, as well as a large number of shrubs, trees, flowers, and weeds.', 'Add a good amount of organic compost or mulch under plants. Mulches will prevent the fungal spores from splashing back up onto flowers and leaves. Copper-Soap fungicides will help by protecting plants from disease spores.\r\n'),
(97, '\r\nHealthy: Zucchini Healthy', ' Zucchini', 'Cucurbita pepo', ' Healthy', 'NIL'),
(98, '\r\nDisease: Zucchini Leaf Curl', 'Zucchini Leaf Curl', 'Cucurbita pepo', 'Zucchini plants showing signs of curled leaves that are stunted, stiff and darker than normal may have contracted curly top virus. This virus causes runner tips to curl, foliage to crinkle and mature plants may yellow and die. Beet leafhoppers transmit this damaging virus, which can severely affect your production.', 'If you control beet leafhoppers from infesting your plants, you will reduce the possibility of the zucchinis developing the virus.'),
(99, 'Healthy: Cotton', 'Cotton', 'Gossypium', 'Healthy', 'NIL'),
(100, 'Disease: Cucumber Mite', 'Cucumber Mite', 'Cucumis sativus', 'Cucumber mite caused by Tetranychus spp. Pest monitoring Infestations usually begin on lower leaves of plants, then progress upwards. Inspect lowest leaves for stippling and webbing first.', 'Isolate the plant and then spray the leaves and stems of then plant with pressure water, like from a hose or faucet. Introduce natural predators to the infected plant. Ladybugs and other parasitic mites that kill mites can be purchased from reputable nurseries. Neem oil or insecticidal oil these substances will cling to them to kill mites rather effectively. Use a miticide, which will be effective for getting rid of mites.\r\n');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dataset`
--
ALTER TABLE `dataset`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
